#!/bin/sh /etc/rc.common

START=99  # Start order of the service (should be high to run it late in the boot process)
SERVICE_USE_PID=1

start() {
    echo "Stopping Passwall"
    /etc/init.d/passwall stop

    echo "Installing xray-core package into RAM..."
    
    # Attempt to install xray-core into RAM
    for i in $(seq 1 3); do
        opkg update
        opkg -d ram install xray-core
        # Check if the installation was successful
        if [ $? -eq 0 ]; then
            echo "xray-core installed successfully into RAM."
            echo "Starting Passwall"
            /etc/init.d/passwall start
            return 0
        else
            echo "Installation attempt $i failed. Retrying in 120 seconds..."
            sleep 120
        fi
    done

    echo "Failed to install xray-core into RAM after 3 attempts."
    return 1
}

stop() {
    # You can implement stopping logic here if needed
    return 0
}

reload() {
    return 0
}

restart() {
    stop
    start
}

boot() {
    start
}
